import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className=" min-h-screen">{children} </main>
        
        <footer className=" bg-blue-50 py-12 ">
          <div className=" container mx-auto px-4 text-center text-green-600">
            <p>  Made With by Ezeslucky</p>
          </div>
        
        </footer>
      </body>
    </html>
  );
}
